// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: protobuff/file-stream.proto

package filestream

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FileStream_Stream_FullMethodName = "/FileStream.FileStream/Stream"
)

// FileStreamClient is the client API for FileStream service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FileStreamClient interface {
	Stream(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[File, Response], error)
}

type fileStreamClient struct {
	cc grpc.ClientConnInterface
}

func NewFileStreamClient(cc grpc.ClientConnInterface) FileStreamClient {
	return &fileStreamClient{cc}
}

func (c *fileStreamClient) Stream(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[File, Response], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FileStream_ServiceDesc.Streams[0], FileStream_Stream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[File, Response]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FileStream_StreamClient = grpc.ClientStreamingClient[File, Response]

// FileStreamServer is the server API for FileStream service.
// All implementations must embed UnimplementedFileStreamServer
// for forward compatibility.
type FileStreamServer interface {
	Stream(grpc.ClientStreamingServer[File, Response]) error
	mustEmbedUnimplementedFileStreamServer()
}

// UnimplementedFileStreamServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFileStreamServer struct{}

func (UnimplementedFileStreamServer) Stream(grpc.ClientStreamingServer[File, Response]) error {
	return status.Errorf(codes.Unimplemented, "method Stream not implemented")
}
func (UnimplementedFileStreamServer) mustEmbedUnimplementedFileStreamServer() {}
func (UnimplementedFileStreamServer) testEmbeddedByValue()                    {}

// UnsafeFileStreamServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FileStreamServer will
// result in compilation errors.
type UnsafeFileStreamServer interface {
	mustEmbedUnimplementedFileStreamServer()
}

func RegisterFileStreamServer(s grpc.ServiceRegistrar, srv FileStreamServer) {
	// If the following call pancis, it indicates UnimplementedFileStreamServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FileStream_ServiceDesc, srv)
}

func _FileStream_Stream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(FileStreamServer).Stream(&grpc.GenericServerStream[File, Response]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FileStream_StreamServer = grpc.ClientStreamingServer[File, Response]

// FileStream_ServiceDesc is the grpc.ServiceDesc for FileStream service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FileStream_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "FileStream.FileStream",
	HandlerType: (*FileStreamServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Stream",
			Handler:       _FileStream_Stream_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "protobuff/file-stream.proto",
}
