// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: protobuff/file-stream.proto

package filestream

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type File struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Size          int32                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *File) Reset() {
	*x = File{}
	mi := &file_protobuff_file_stream_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *File) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*File) ProtoMessage() {}

func (x *File) ProtoReflect() protoreflect.Message {
	mi := &file_protobuff_file_stream_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use File.ProtoReflect.Descriptor instead.
func (*File) Descriptor() ([]byte, []int) {
	return file_protobuff_file_stream_proto_rawDescGZIP(), []int{0}
}

func (x *File) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *File) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_protobuff_file_stream_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_protobuff_file_stream_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_protobuff_file_stream_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Response) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_protobuff_file_stream_proto protoreflect.FileDescriptor

const file_protobuff_file_stream_proto_rawDesc = "" +
	"\n" +
	"\x1bprotobuff/file-stream.proto\x12\n" +
	"FileStream\".\n" +
	"\x04File\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x05R\x04size\">\n" +
	"\bResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess2@\n" +
	"\n" +
	"FileStream\x122\n" +
	"\x06Stream\x12\x10.FileStream.File\x1a\x14.FileStream.Response(\x01B\x18Z\x16./protobuff;filestreamb\x06proto3"

var (
	file_protobuff_file_stream_proto_rawDescOnce sync.Once
	file_protobuff_file_stream_proto_rawDescData []byte
)

func file_protobuff_file_stream_proto_rawDescGZIP() []byte {
	file_protobuff_file_stream_proto_rawDescOnce.Do(func() {
		file_protobuff_file_stream_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protobuff_file_stream_proto_rawDesc), len(file_protobuff_file_stream_proto_rawDesc)))
	})
	return file_protobuff_file_stream_proto_rawDescData
}

var file_protobuff_file_stream_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protobuff_file_stream_proto_goTypes = []any{
	(*File)(nil),     // 0: FileStream.File
	(*Response)(nil), // 1: FileStream.Response
}
var file_protobuff_file_stream_proto_depIdxs = []int32{
	0, // 0: FileStream.FileStream.Stream:input_type -> FileStream.File
	1, // 1: FileStream.FileStream.Stream:output_type -> FileStream.Response
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protobuff_file_stream_proto_init() }
func file_protobuff_file_stream_proto_init() {
	if File_protobuff_file_stream_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protobuff_file_stream_proto_rawDesc), len(file_protobuff_file_stream_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protobuff_file_stream_proto_goTypes,
		DependencyIndexes: file_protobuff_file_stream_proto_depIdxs,
		MessageInfos:      file_protobuff_file_stream_proto_msgTypes,
	}.Build()
	File_protobuff_file_stream_proto = out.File
	file_protobuff_file_stream_proto_goTypes = nil
	file_protobuff_file_stream_proto_depIdxs = nil
}
